language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
script:
  - ./gradlew clean assemble || ./gradlew clean assemble

